connect 'jdbc:derby:ITP_database;create=true';

drop table publisher;
drop table format;
drop table author;
drop table genre;
drop table book;

create table publisher (
	publisherID integer not null generated by default as identity,
	name long varchar,
	constraint publisher_primary_key primary key (publisherID)
);

create table format (
	formatID integer not null generated by default as identity,
	name long varchar,
	constraint format_primary_key primary key (formatID)
);

create table author (
	authorID integer not null generated by default as identity,
	name long varchar,
	constraint author_primary_key primary key (authorID) 
);

create table genre (
	genreID integer not null generated by default as identity,
	name long varchar,
	constraint genre_primary_key primary key (genreID)
);

create table book (
	ISBN integer,
	authorID integer,
	publisherID integer,
	genreID integer,
	formatID integer,
	constraint book_primary_key primary key (ISBN),
	foreign key (authorID) references author (authorID),
	foreign key (publisherID) references publisher (publisherID),
	foreign key (genreID) references genre (genreID),
	foreign key (formatID) references format (formatID)
);

disconnect;
exit;